// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAutomaticModeChange();
void onFanChange();
void onHeaterChange();
void onHumidityDisplayChange();

int h_logF;
int humidity;
int temp;
int t_logF;
bool automatic_mode;
bool fan;
bool heater;
bool humidity_display;

void initProperties(){

  ArduinoCloud.addProperty(h_logF, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(humidity, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(temp, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(t_logF, READ, 1 * SECONDS, NULL);
  ArduinoCloud.addProperty(automatic_mode, READWRITE, ON_CHANGE, onAutomaticModeChange, 1);
  ArduinoCloud.addProperty(fan, READWRITE, ON_CHANGE, onFanChange);
  ArduinoCloud.addProperty(heater, READWRITE, ON_CHANGE, onHeaterChange);
  ArduinoCloud.addProperty(humidity_display, READWRITE, ON_CHANGE, onHumidityDisplayChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
